stages:
  - test
  - build

simple_test_job:
  stage: test
  script:
    - echo "Запуск тестового шага..."
    - echo "Тесты пройдены ✅"

simple_build_job:
  stage: build
  script:
    - echo "Начинаем сборку..."
    - sleep 3
    - echo "Сборка завершена ✅"